# Generated by Django 3.2.7 on 2021-11-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regestration', '0003_auto_20211130_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('sn', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
