# Generated by Django 3.2.7 on 2021-11-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regestration', '0004_auto_20211130_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bc_img', models.ImageField(upload_to='')),
                ('title', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Postt',
        ),
    ]
