# Generated by Django 3.2.7 on 2021-11-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regestration', '0005_auto_20211130_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='bc_img',
            field=models.ImageField(upload_to='templates/image'),
        ),
    ]
