# Generated by Django 3.2.7 on 2022-01-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regestration', '0008_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='block_color',
            field=models.TextField(default='#000000'),
        ),
        migrations.AddField(
            model_name='intro',
            name='text_color',
            field=models.TextField(default='#000000'),
        ),
    ]
