# Generated by Django 3.2.7 on 2022-02-08 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regestration', '0009_auto_20220118_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сrutch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regestration.intro')),
            ],
        ),
    ]
