# Generated by Django 3.2.7 on 2022-02-08 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regestration', '0010_сrutch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сrutch',
            new_name='copy',
        ),
    ]
