# Generated by Django 3.2.7 on 2022-02-08 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regestration', '0011_rename_сrutch_copy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='copy',
        ),
        migrations.DeleteModel(
            name='Intro',
        ),
    ]
