# Generated by Django 3.2.7 on 2022-02-08 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regestration', '0015_intro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Intro',
        ),
    ]
