# Generated by Django 3.2.7 on 2022-02-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regestration', '0017_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='subtitle',
            field=models.TextField(default='Описание'),
        ),
    ]
